# Generated by Django 4.1.1 on 2022-10-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="User name")),
                ("email", models.EmailField(max_length=150, verbose_name="User email")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Rating"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="format: y-m-d H:M:S",
                        verbose_name="date product image created",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reviews",
                "ordering": ("-created_at",),
            },
        ),
    ]
