# Generated by Django 4.1.1 on 2022-10-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_media_alt_text"),
        ("cart", "0002_alter_cartitem_cart_cartitemattribute"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="cartitemattribute",
            unique_together={("item", "attribute_value")},
        ),
    ]
