# Generated by Django 4.1.1 on 2022-10-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                error_messages={
                    "name": {"max_length": "the price must be between 0 and 9999.99."}
                },
                help_text="format: maximum price 999.99",
                max_digits=7,
                verbose_name="total price",
            ),
        ),
    ]
